"""update models

Revision ID: e8a61d4f41af
Revises:
Create Date: 2024-06-26 07:57:44.720688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = "e8a61d4f41af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "email",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "username",
            sqlmodel.sql.sqltypes.AutoString(length=30),
            nullable=False,
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_user_id"), "user", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_username"), "user", ["username"], unique=True
    )
    op.create_table(
        "product",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column("number_in_stock", sa.Integer(), nullable=False),
        sa.Column(
            "unit_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "product_owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("product_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_owner_id"], ["user.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_index(
        op.f("ix_product_product_id"), "product", ["product_id"], unique=False
    )
    op.create_table(
        "image",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("image_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("product_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.product_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("image_id"),
    )
    op.create_index(
        op.f("ix_image_image_id"), "image", ["image_id"], unique=False
    )
    op.create_table(
        "order",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("order_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("product_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.product_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_index(
        op.f("ix_order_order_id"), "order", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_order_id"), table_name="order")
    op.drop_table("order")
    op.drop_index(op.f("ix_image_image_id"), table_name="image")
    op.drop_table("image")
    op.drop_index(op.f("ix_product_product_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
